modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="ARR"

[[mods]]
modId="redline"
displayName="Redline"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
description='''
This addonpack adds cyberware.
'''

[[dependencies.test]]
modId = "palladium"
mandatory = true
versionRange = ""
ordering = "NONE"
side = "BOTH"